# Generated by Django 4.2.5 on 2023-10-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateField()),
                ('pilot_name', models.CharField(max_length=200)),
                ('flight_summary', models.TextField()),
                ('departure_location', models.CharField(max_length=200)),
                ('landing_location', models.CharField(max_length=200)),
                ('takeoff_time', models.TimeField()),
                ('landing_time', models.TimeField()),
                ('flight_time', models.DurationField()),
                ('total_flight_time', models.DurationField()),
                ('safety_issues', models.TextField()),
            ],
        ),
    ]
